export { loadConfig, getDefaultConfig } from './config.js';
export type { SuperSpecConfig, Strategy } from './config.js';
export { resolveTemplatePath, copyTemplate, renderTemplate, writeRenderedTemplate } from './template.js';
export { lintArtifact, lintChange } from './lint.js';
export type { LintResult } from './lint.js';
export { parseFrontmatter, serializeFrontmatter, updateFrontmatter, addDependency, removeDependency } from './frontmatter.js';
export type { Frontmatter, ParsedDoc } from './frontmatter.js';
export { validateChange } from './validate.js';
export type { ValidationIssue } from './validate.js';
export { generateContext } from './context.js';
export type { ContextData } from './context.js';
